version: '3'  

services:
  server:
    image: server
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database-postgres  
    ports:
      - "8800:8800"  
    restart: always
    networks:
      - server-network
  
  database-postgres:  
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: munai
    volumes:
      - ./app/migrations:/var/lib/postgresql/migrations
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - server-network

networks:  
  server-network:
    driver: bridge

volumes:
  database: